[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
rogue_staking = "3cvusCxiUv88YsuaDqNEVXYtPVbdmsqSRQRP2gc5riP4"

[programs.localnet]
rogue_staking = "3cvusCxiUv88YsuaDqNEVXYtPVbdmsqSRQRP2gc5riP4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.test.ts"
test_deposit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deposit.test.ts"
test_initialize_platform_config = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initializePlatformConfig.test.ts"
test_withdraw = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw.test.ts"
