[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rogue_staking = "73iU3kEfpJQhCpLaFBMAaYDVwSM5RHwhWqHBW6XGDYU1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
